### ISSUE TITLE
USER STORY: Create Wireframes

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#1]
As a **developer**, I want **to create wireframes** to **visualize the layout and structure of the web application**.

### Acceptance Criteria

- [x] Wireframes should include key components such as navigation menus, content sections, and interactive elements.
- [x] Wireframes should reflect the user flow and interactions within the application.
- [x] Wareframes should have a responsive design and have all the necessary site elements for small, medium and large screens.

### Tasks:
- [x] Gather requirements and user stories to understand the functionality needed in the wireframes.
- [x] Create detailed wireframes for small screens using a wireframing tool like Balsamiq.
- [x] Create detailed wireframes for medium screens using a wireframing tool like Balsamiq.
- [x] Create detailed wireframes for large screens using a wireframing tool like Balsamiq.
- [x] Add the information to the redmi.md file
