### ISSUE TITLE
USER STORY: Sign IN and SIgn OUT functionality

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#12]
As a **role** I can **capability** so that **received benefit**
As a **Registered User**, I want to be able to **sign in and sign of the account** so that I can **use the platform**.

### **Acceptance Criteria:**

- [x] Users can access a login form.
- [x] Users can input their username and password.
- [x] Valid credentials allow users to log in successfully.
- [x] Invalid credentials display appropriate error messages.
- [x] Display option to log out.
- [ ] Display confirmation with username.

### **Tasks:**

- [x] Implement backend authentication for user login.
- [x] Verify user credentials and allow access upon successful login.
- [x] Set up error messages for invalid login attempts.
- [x] Set up confirmation of successful log out.
