### ISSUE TITLE
USER STORY: Manage Comments

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#17]
As a **Registered User**, I want to **be able to delete and edit comments**.

### **Acceptance Criteria:**

- [x] Confirmation message indicating the comment has been updated.
- [x]  Only registered comment authors can access the delete option.
- [x]  User attempt to delete the comment so they are prompted to confirm the deletion before it is permanently removed.
- [x] Only registered comment authors can access the delete option.

### **Tasks:**

- [x] Implement an "Edit" button that is accessible to authenticated authors of comments, allowing them to modify their comments.
- [x] Design and set up a template for rendering the comment editing form, ensuring a user-friendly interface for authors.
- [x] Implement error messaging and feedback mechanisms to notify authors of any issues.
- [x] Add notifications to confirm successful comment editing
