### ISSUE TITLE
USER STORY: Create database structure

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#2]
As a Developer I can make web application database relevant structure

### **Acceptance Criteria:**

- [x] A list of agreed models for further creation of the database structure.
- [x]  The structure of the database must conform to the agreed models.

### **Tasks:**

- [x] Create a list of models that will be used in the database
- [x] Create a database model that corresponds to the agreed models
- [x] Add the information to the redmi file
