### ISSUE TITLE
EPIC 3: about

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#20]
SUMMARY: 
This Epic covers the basic layout and information of the site

- [x] https://github.com/barkode/storelinks/issues/10
- [x] https://github.com/barkode/storelinks/issues/13
- [x] https://github.com/barkode/storelinks/issues/11
- [x] https://github.com/barkode/storelinks/issues/21
