### ISSUE TITLE
USER STORY: As a Developer I would like the user to see custom error pages to provide good user experience

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#21]
As a **role** I can **capability** so that **received benefit**

### **Acceptance Criteria:**

- [x] If an error occurs the relevant custom page is shown
- [x]  There is a link to the home page

### **Tasks:**

- [x] Create 404.html template
- [x] Create 500.html template
- [x] Create 400.html template
- [x] Create 403.html template
