### ISSUE TITLE
EPIC 4: Authorization

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#22]
Implement user authorization
SUMMARY: 

- [x] https://github.com/barkode/storelinks/issues/12
- [x] https://github.com/barkode/storelinks/issues/28
- [x] https://github.com/barkode/storelinks/issues/29
