### ISSUE TITLE
EPIC 5 : SignIn and SignOut

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#24]
SUMMARY: 

- [x] https://github.com/barkode/storelinks/issues/30
- [x] https://github.com/barkode/storelinks/issues/31
- [x] https://github.com/barkode/storelinks/issues/32
