### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#28]
As a Site User I can clearly see how to navigate the site so I can find what I'm looking for

### **Acceptance Criteria:**

- [ ] The navigation bar is visible with all possible links
- [ ]  The Logo and Home link to Home
- [ ]  The Home link is active when on this page
- [ ] The Footer is at the bottom

### **Tasks:**

- [ ] Add navigation bar with all logo and all possible links to base template
- [ ] Add footer to base template
- [ ] Add href to Logo and Home link
- [ ] Add active on Home link when on Home page
