### ISSUE TITLE
USER STORY: Movie detail page

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#29]
As Site Admin I can create different Films profiles so the website can display their information

### **Acceptance Criteria:**

- [ ]  You can see Film details

### **Tasks:**

- [ ] Add URL links to base.html
- [ ] Create html, CSS and Javascript layout for page
- [ ] Create view, URL and film_detail.html
