### ISSUE TITLE
USER STORY: Use Agile methodology

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#3]
As a **developer**, I can use Agile methodology  so that to **ensure speed of development** and **high quality of the application**.

### **Acceptance Criteria:**

- [x]  Understand the basic principles of working with the Agile methodology.
- [x] Use agile practices in work such as user stories, sprints, epics.

### **Tasks:**

- [x] Create a project backlog that will meet the requirements and criteria of user stories
- [x] Break large tasks into smaller ones.
- [x] Analyze tasks and determine priorities for further development.
- [x] Use the MoSCoW method for prioritizing tasks
