### ISSUE TITLE
USER STORY: User profile page

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#30]
As a Logged in member I would like to have an area where I can see all my comments

### **Acceptance Criteria:**

- [ ] Be able to view a member area page where only logged in members can visit
- [ ]  Acceptance criteria 2
- [ ]  Acceptance criteria 3

### **Tasks:**

- [ ] Create view.
- [ ] Add active on member area
- [ ] Add URL links to base.html and only show to logged in user
