### ISSUE TITLE
USER STORY: SignIn and SignOut

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#31]
As a Site User I want to log in and out so I can interact with the site content

### **Acceptance Criteria:**

- [x] A user can sign in and sign out

### **Tasks:**

- [x] Add authentication appropriate links to navigation bar for log in and log out
- [x] Customise log in template
- [x] Customise log out template
- [x] Add active on log in and log out navigation link
