### ISSUE TITLE
USER STORY: Member Registration

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#32]
As a Site User I can register as a member so I can interact with the site content

### **Acceptance Criteria:**

- [x] A user can register an account

### **Tasks:**

- [x] Add authentication appropriate links to navigation bar for registration
- [x] Customise registration template
