### ISSUE TITLE
USER STORY: Design Website Structure

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#33]
As a Developer I know my website structure so I can create the relevant features

### **Acceptance Criteria:**

- [x] Database model diagram has been created
- [x]  Wire frames have been created

### **Tasks:**

- [x] Create model structure diagram
- [x] Create wire frames for all possible pages
