### ISSUE TITLE
USER STORY: Add Movie Information

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#34]
As Site Admin I can create different Films profiles so the website can display their information

### **Acceptance Criteria:**

- [ ] The ability for site Admin to create new Film objects on Admin site

### **Tasks:**

- [ ] Get all film information
- [ ] Create modal with relevant fields
- [ ] Customize Admin film area
