### ISSUE TITLE
EPIC 1: Planning

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#4]
Epic covers the planning for the project

- [x] https://github.com/barkode/storelink/issues/1
- [x] https://github.com/barkode/storelink/issues/2
- [x] https://github.com/barkode/storelink/issues/3
