### ISSUE TITLE
BUG: CRUD problems

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#42]
While creating movie comments work, trying to edit them results in a handled error page - https://storelinks-ff093b7a4c54.herokuapp.com/movies/movie/batman-begins/edit_comment/19. There seems to be some delete functionality in the code for the movie comments, but there is no button rendered on the UI as well.

### **ERROR:**

- [x] Error when try to edit comment
- [x]  No "DELETE" button 
- [x]  Fix some styles

### **Tasks:**

- [x] Check CRUD functionality
- [x] Add "DELETE" button
- [x] Check how delete button works
- [x] Fix some UI errors
