### ISSUE TITLE
EPIC 2: Development Environment

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#5]
- [x] https://github.com/barkode/storelinks/issues/6
- [x] https://github.com/barkode/storelinks/issues/7
- [x] https://github.com/barkode/storelinks/issues/8
- [x] https://github.com/barkode/storelinks/issues/9
