### ISSUE TITLE
USER STORY: Development Environment

### ISSUE THREAD

**Issue by barkode** [barkode/storelinks#6]
As a Developer I need an development environment so I can create the web application

### **Acceptance Criteria:**

- [x] Have a working development environment
- [x]  Installed all needed packages

### **Tasks:**

- [x] Create workspace
- [x] Install relevant packages add requirements and hide relevant environment variables
